/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-item` | `/add-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-doll` | `/my-doll`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/outfits` | `/outfits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wardrobe` | `/wardrobe`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-item` | `/add-item`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-doll` | `/my-doll`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/outfits` | `/outfits`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/wardrobe` | `/wardrobe`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-item${`?${string}` | `#${string}` | ''}` | `/add-item${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-doll${`?${string}` | `#${string}` | ''}` | `/my-doll${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/outfits${`?${string}` | `#${string}` | ''}` | `/outfits${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/wardrobe${`?${string}` | `#${string}` | ''}` | `/wardrobe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-item` | `/add-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-doll` | `/my-doll`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/outfits` | `/outfits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wardrobe` | `/wardrobe`; params?: Router.UnknownInputParams; };
    }
  }
}
